sudo userdel -r OctaviaBlake
sudo userdel -r BellamyBlake
sudo userdel -r AbigailGriffin
sudo userdel -r FinnCollins
sudo userdel -r JasperJordan
sudo userdel -r RavenReyes
sudo userdel -r MontyGreen
sudo userdel -r ClarkeGriffin
sudo userdel -r JohnMurphy
sudo userdel -r WellsJaha
sudo userdel -r MarcusJane
sudo userdel -r PrenomNom
sudo userdel -r MaddyGriffin
